[project]
name = "holospooky"
version = "1"
authors = [
  { name = "montypythonist", email = "julia.alotoom.contact@gmail.com" },
]
description = "Unofficial fixed module + pre-built programs + self-made features for Cozmo SDK"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = { file = "LICENSE" }

[project.urls]
Homepage = "https://github.com/montypythonist/holospooky"