[project]
    name            = "retrievableset"
    version         = "0.2.2"
    dependencies    = []
    requires-python = ">=3.10"
    authors         = [{name = "oeykmiih", email = "joao@kyeo.xyz"}]
    description     = "A collection to add and retrieve objects by its hashs."
    keywords        = ["Collection"]
    classifiers     = ["License :: OSI Approved :: MIT License"]
    urls            = {repository = "https://codeberg.org/oeykmiih/py_retrievableset"}

[build-system]
    requires      = ["setuptools"]
    build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
    where = ["source"]

[tool.mypy]
    exclude               = ["source/**/_vendor"]
    strict                = true
    disallow_untyped_defs = true
    strict_equality       = true
    local_partial_types   = true

[tool.pyright]
    exclude    = ["source/**/_vendor"]
    extraPaths = ["source"]

[tool.pytest.ini_options]
    minversion = "6.0"
    addopts    = ["-rf"]
    pythonpath = ["source"]
    testpaths  = ["tests", "source/**/tests"]
