[project]
name = "kisti-dongmin-naver-news-crawler"
version = "0.3.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "build>=1.3.0",
    "mcp[cli]>=1.12.3",
    "requests>=2.32.4",
    "twine>=6.1.0",
]

[project.scripts]
kisti-dongmin-naver-news-crawler = "kisti_dongmin_naver_news_crawler:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
