[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "m24842_ml"
version = "1.3.7"
description = "Collection of ML models and benchmarking tools"
requires-python = ">=3.8"
dependencies = [
    "torch",
    "transformers",
    "einops",
    "opt_einsum",
    "rotary_embedding_torch",
    "wandb",
    "pyyaml",
]