[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "trackerpkg"
version = "0.1.1"
description = "Token and resource usage tracker for OpenAI API calls with optional PostgreSQL logging"
authors = [
  { name = "Ali Naveed", email = "ali@dynastack.ai" }
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
dependencies = [
  "psutil",
  "psycopg2-binary",
  "python-dotenv"
]
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
  "License :: OSI Approved :: MIT License"
]

[tool.setuptools.packages.find]
where = ["src"]
