[tool.poetry]
name = "eric-redis-queues"
description = "Redis support for eric-sse"
version = "1.0.0a7"
authors = ["Luca Stretti <laxertu@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.urls]
Homepage = "https://laxertu.github.io/eric"
Repository = "https://github.com/laxertu/eric-redis-queues"
Issues = "https://github.com/laxertu/eric/issues"

[tool.poetry.dependencies]
python = ">=3.10, <3.12"
redis = "^5.2.1"
eric-sse = "^1.0.0a11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
