[[pages]]
path = "pages/home.py"
name = "Home"
icon = ":house:"

# [[pages]]
# name = "Applications"
# icon = ":books:"
# is_section = true

[[pages]]
path = "pages/calctime.py"
name = "Time Calculator"
icon = ":alarm_clock:"

[[pages]]
path = "pages/parsepayslip.py"
name = "Payslip Parser"
icon = ":dollar:"

[[pages]]
path = "pages/filesmanager.py"
name = "Files Manager"
icon = ":card_file_box:"

[[pages]]
name = "Movies Manager"
icon = ":clapper:"
is_section = true

[[pages]]
path = "pages/moviesorter.py"
name = "Movies Sorter"
icon = ":card_index_dividers:"

[[pages]]
path = "pages/moviegenretagger.py"
name = "Genre Tagger"
icon = ":label:"

[[pages]]
path = "pages/moviessummarizer.py"
name = "Movies Summarizer"
icon = ":memo:"

[[pages]]
path = "pages/moviefetcher.py"
name = "Movies Fetcher"
icon = ":mag:"
