[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "continua"
dynamic = ["version"]
description = 'Continual Learning Framework for Transformers'
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
keywords = []
authors = [
    { name = "Yasas Senarath", email = "12231659+ysenarath@users.noreply.github.com" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "numba",
    "umap-learn>=0.5.7",
    "datasets>=3.1.0",
    "matplotlib>=3.7.5",
    "numpy==1.26.4",
    "pandas>=2.0.3",
    "scikit-learn>=1.3.2",
    "seaborn>=0.13.2",
    "setfit>=1.1.1",
    "nightjar>=0.0.5",
    "quadprog>=0.1.13",
    "hydra-core>=1.3.2",
    "optuna>=4.3.0",
    "dash>=3.0.4",
    "plotly>=6.0.1",
    "dash-bootstrap-components>=2.0.2",
    "diskcache>=5.6.3",
    "flask-migrate>=4.1.0",
    "flask-sqlalchemy>=3.1.1",
    "flask-login>=0.6.3",
    "flask>=3.0.3",
    "textkit-learn>=0.3.9",
    "torch>=2.3.1",
    "transformers>=4.45.2",
    "adapters>=1.0.1",
    "jupyter>=1.1.1",
    "jupyterlab>=4.4.4",
    "easysubmit[scalene]==0.2.3",
]

[project.urls]
Documentation = "https://github.com/ysenarath/continua#readme"
Issues = "https://github.com/ysenarath/continua/issues"
Source = "https://github.com/ysenarath/continua"

[tool.hatch.version]
path = "src/continua/__init__.py"

[tool.hatch.envs.types]
extra-dependencies = ["mypy>=1.0.0"]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/continua tests}"

[tool.coverage.run]
source_pkgs = ["continua", "tests"]
branch = true
parallel = true
omit = []

[tool.coverage.paths]
continua = ["src/continua", "*/continua/src/continua"]
tests = ["tests", "*/continua/tests"]

[tool.coverage.report]
exclude_lines = ["no cov", "if __name__ == .__main__.:", "if TYPE_CHECKING:"]

[tool.ruff.lint.pydocstyle]
convention = "numpy" # Accepts: "google", "numpy", or "pep257".

# [project.scripts]
# continua = "continua.misc.main:cli"

[tool.uv.sources]
textkit-learn = { git = "git+ssh://git@github.com/ysenarath/textkit-learn" }
fasttext = { git = "https://github.com/facebookresearch/fastText" }
