[project]
name = "frameon"
version = "0.1.2"
description = "Frameon extends pandas DataFrame with analysis methods while keeping all original functionality intact."
authors = [
    {name = "Pavel Grigoryev",email = "pavel.grigoryev.ds@gmail.com"}
]
readme = "README.md"
license = "MIT"
requires-python = ">=3.11"
keywords = ["pandas", "data-analysis", "data-science"]
dependencies = [
    "numpy (>=2.3.2,<3.0.0)",
    "pandas (>=2.3.1,<3.0.0)",
    "pingouin (>=0.5.5,<0.6.0)",
    "plotly (>=6.2.0,<7.0.0)",
    "scikit-learn (>=1.7.1,<2.0.0)",
    "scipy (>=1.16.0,<2.0.0)",
    "statsmodels (>=0.14.5,<0.15.0)",
    "tqdm (>=4.67.1,<5.0.0)",
    "textblob (>=0.19.0,<0.20.0)",
    "wordcloud (>=1.9.4,<2.0.0)",
    "rich (>=14.0.0,<15.0.0)",
    "scikit-posthocs (>=0.11.4,<0.12.0)",
    "nltk (>=3.9.1,<4.0.0)",
    "kaleido (>=1.0.0,<2.0.0)",
    "ipython (>=9.4.0,<10.0.0)"
]

[project.urls]
Homepage = "https://github.com/PavelGrigoryevDS/frameon"
Documentation = "https://frameon.readthedocs.io/en/latest"
Repository = "https://github.com/PavelGrigoryevDS/frameon"
Issues = "https://github.com/PavelGrigoryevDS/frameon/issues"

[tool.poetry]
packages = [{include = "frameon", from = "src"}]

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.30.0"
jupyter = "^1.1.1"
build = "^1.2.2.post1"
jinja2 = "^3.1.6"
publish = {version = "^0.3.6", python = "<3.14"}

[tool.poetry.group.docs.dependencies]
sphinx = "^8.2.3"
pydata-sphinx-theme = "^0.16.1"
sphinx-copybutton = "^0.5.2"
sphinx-autodoc-typehints = "^3.2.0"
myst-parser = "^4.0.1"
myst-nb = "^1.3.0"
ipykernel = "^6.30.0"
linkify-it-py = "^2.0.3"
sphinx-gallery = "^0.19.0"
sphinx-favicon = "^1.0.1"
sphinxemoji = "^0.3.1"
sphinx-tabs = "^3.4.7"
sphinx-togglebutton = "^0.3.2"
sphinx-comments = "^0.0.3"
sphinx-design = "^0.6.1"
sphinx-issues = "^5.0.1"
sphinx-autoapi = "^3.6.0"
sphinx-plotly-directive = "^0.1.3"
sphinx-exec-directive = "^0.6"

[tool.poetry.group.test.dependencies]
pytest = "^8.4.1"
pytest-cov = "^6.2.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"] 

[tool.coverage.run]
source = ["src/frameon"]  
omit = [
    "*/tests/*",
    "*/__init__.py",
    "*/_version.py",
    "src/frameon/utils/*",    
    "src/frameon/datasets/*",
    "src/frameon/utils/plotting/*"  
]
