[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "zafiaonline"
version = "6.0.2"
keywords = ["Mafia Online API"]
description = "A Python API library for interacting with Mafia Online game."
requires-python = ">=3.9"
license = { text = "LGPL-2.1" }
authors = [
    { name = "unelected" }
]

dependencies = [
    "websockets >= 15.0.1",
    "msgspec",
    "sphinx",
    "aiohttp",
    "pyyaml"
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"zafiaonline.transport" = ["*.yaml"]
