[tool.poetry]
name = "nonebot-plugin-delta-helper"
version = "0.11.0"
description = ""
authors = ["Irelia <1074822720@qq.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
nonebot2 = "^2.4.2"
nonebot-adapter-onebot = "^2.4.6"
httpx = ">=0.28.1"
nonebot-plugin-orm = "^0.8.2"
nonebot-plugin-apscheduler = "^0.5.0"
nonebot-plugin-send-anything-anywhere = "^0.7.1"
sqlalchemy = "^2.0.41"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
