# Other project metadata fields as specified in:
# https://packaging.python.org/en/latest/specifications/declaring-project-metadata/
# https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "core-https"
description = "This project/library contains common elements related to HTTP & API services..."
version = "1.1.6"

authors = [
    {name = "Alejandro Cora González", email = "alek.cora.glez@gmail.com"}
]

maintainers = [
    {name = "Alejandro Cora González"}
]

requires-python = ">=3.7"
license = {text = "MIT"}
readme = "README.md"

classifiers = [
    # Classifiers -> https://pypi.org/classifiers/
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Developers",
    "Development Status :: 5 - Production/Stable",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13"
]

dependencies = [
    "core-mixins>=1.1.2",
    "core-tests>=1.1.0",
    "urllib3>=2.2.3; python_version >= '3.8'",
    "urllib3>=1.26.20; python_version >= '3.7' and python_version < '3.8'",
    "typing-extensions>=4.8.0; python_version >= '3.8' and python_version < '3.11'",
    "typing-extensions>=4.2.0; python_version >= '3.7' and python_version < '3.8'"
]

[project.optional-dependencies]
docs = [
    "pydata-sphinx-theme==0.16.1",
    "Sphinx==8.2.3"
]

[project.urls]
Homepage = "https://gitlab.com/bytecode-solutions/core/core-https"
Repository = "https://gitlab.com/bytecode-solutions/core/core-https"
Documentation = "https://core-https.readthedocs.io/en/latest/"
Issues = "https://gitlab.com/bytecode-solutions/core/core-https/-/issues"
Changelog = "https://gitlab.com/bytecode-solutions/core/core-https/-/blob/master/CHANGELOG.md"
