[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mojiza"
version = "0.1.2"        # â† bumped patch version
description = "A lightweight Python web framework"
authors = [
  { name = "Abdulhodiy", email = "muhiddinovabdulhodiy2@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.7"
license = { text = "GPL-3.0-only" }
dependencies = [
  "aiosqlite",
  "Jinja2>=3.1.4",
  "loguru>=0.7.3",
  "watchdog>=6.0.0",
  "aiohttp>=3.11.10",
  "qrcode>=8.0",
]

classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
  "Operating System :: OS Independent",
]
