[build-system]
requires = ["flit_core>=3.4"]
build-backend = "flit_core.buildapi"

[project]
name =  "magma-ven"
version = "0.0.3"
authors = [
    {name = "Martanto", email = "martanto@live.com"},
    {name = "Devy Kamil Syahbana", email = "devy.syahbana@gmail.com"},
    {name = "Syarif Abdul Manaf", email = "riefmof@gmail.com"},
]
description = "MAGMA Volcano Eruption Notice (VEN)"
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["magma", "indonesia", "volcano", "eruption", "magma indonesia", "volcanoes"]
requires-python = ">=3.11"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.2.2",
    "numpy>=2.2.5",
    "matplotlib>=3.9.0",
    "magma-database>=1.5.0",
    "magma-auth",
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

[project.optional-dependencies]
dev = [
    "black[d]",
    "isort",
    "openpyxl",
    "pandas",
    "numpy",
    "matplotlib",
    "magma-database",
    "magma-auth",
]

[project.urls]
Homepage = "https://github.com/martanto/magma-ven"
Issues = "https://github.com/martanto/magma-ven/issues"