[project]
name = "tfv_get_tools"
version = "0.2.3"
description = "Tool for downloading and processing data for TUFLOW FV modelling"
authors = [
    { name = "Alex Waterhouse", email = "alex.waterhouse@apac.bmt.org" },
    { name = "Mitchell Smith", email = "mitchell.smith@apac.bmt.org" },
    { name = "TUFLOW Support", email = "support@tuflow.com" },
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.9,<3.14"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "netCDF4>=1.6.2",
    "tqdm>=4.65.0",
    "xarray>=2023.1.0",
    "scipy>=1.10.0",
    "pyproj>=3.5.0",
    "siphon>=0.9",
    "cdsapi>=0.7.0",
    "copernicusmarine>=1.2.3",
    "bottleneck>=1.3.5",
    "pyTMD>=2.1.5",
    "shapely >= 2.0.6",
    "geopandas >= 1.0.1",
]

[project.optional-dependencies]
dev = [
    "ipython>=8.6.0",
    "notebook>=6.5.2",
    "ipykernel>=6.17.1",
    "dask>=2022.11.0",
    "black>=22.12.0",
    "matplotlib>=3.7.0",
    "sphinx>=7.3.7",
    "recommonmark>=0.7.1",
    "sphinx-markdown-builder>=0.6.6",
    "pyprojroot",
]

[project.urls]
Homepage = "https://gitlab.com/tuflow-user-group/tuflow-fv/data-pre-processing/tfv-get-tools"
Repository = "https://gitlab.com/tuflow-user-group/tuflow-fv/data-pre-processing/tfv-get-tools"
Issues = "https://gitlab.com/tuflow-user-group/tuflow-fv/data-pre-processing/tfv-get-tools/issues"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
GetAtmos = "tfv_get_tools.cli.atmos_cli:entry"
GetOcean = "tfv_get_tools.cli.ocean_cli:entry"
GetWave = "tfv_get_tools.cli.wave_cli:entry"
GetTide = "tfv_get_tools.cli.tide_cli:entry"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
tfv_get_tools = ["**/*.yaml", "**/*.yml"]

[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
