[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "burpdrop"
version = "1.2.0"
authors = [
  { name="Gashaw Kidanu", email="kidanugashaw@gmail.com" },
]
description = "A cross-platform Burp Suite CA Certificate installer for Android devices"
readme = "README.md"
requires-python = ">=3.7"
license = { text = "MIT License" }  # This is the correct, non-deprecated way to specify the license.
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Security",
    "Topic :: Utilities",
]
keywords = ["android", "burpsuite", "certificate", "installer", "root", "magisk", "interception", "security"]
dependencies = [
    "requests",
    "colorama"
]

[project.urls]
"Homepage" = "https://github.com/Gashaw512/android-traffic-interception-guide"
"Bug Tracker" = "https://github.com/Gashaw512/android-traffic-interception-guide/issues"

[project.scripts]
burpdrop = "scripts.main:main"

[tool.setuptools.package-data]
"scripts" = ["config.json", "requirements.txt"]

[tool.setuptools.packages.find]
where = ["."]
include = ["scripts*"]