[project]
name = "xproject"
version = "0.0.1"
description = ""
authors = [
    {name = "mathewgeola",email = "mathewgeola@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "furl (>=2.1.4,<3.0.0)",
    "tldextract (>=5.3.0,<6.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "arrow (>=1.3.0,<2.0.0)",
    "fake-useragent (>=2.2.0,<3.0.0)",
    "pillow (>=11.3.0,<12.0.0)",
    "pillow-avif-plugin (>=1.5.2,<2.0.0)",
    "w3lib (>=2.3.1,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
