[project]
name = "pylipextractor"
version = "2.2.4"
description = "A Python package for robust lip frame extraction from videos using MediaPipe, featuring enhanced stability, configurable options, and customizable GPU-accelerated lossless video format conversion for VSR tasks."
readme = "README.md"
authors = [
    { name = "Mehrad Yaghoubi", email = "mehradyaghoubi96@gmail.com" },
]
requires-python = ">=3.8"
dependencies = [
    "opencv-python>=4.5.0",
    "numpy>=1.20.0",
    "mediapipe>=0.10.11",
    "av>=10.0.0",
]
keywords = ["lip-extraction", "visual-speech-recognition", "mediapipe", "video-processing", "lip-reading", "ffmpeg", "video-conversion", "documentation", "examples"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Multimedia :: Video",
]

[project.urls]
Homepage = "https://github.com/MehradYaghoubi/pylipextractor"
"Bug Tracker" = "https://github.com/MehradYaghoubi/pylipextractor/issues"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["pylipextractor*"]

