[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["typing_unknown"]

[project]
name = "typing-unknown"
version = "0.1.2"
requires-python = ">=3.12"
description = "Defines Unknown type for Python"
authors = [
    {name = "Ryan Young", email = "dev@ryayoung.com"}
]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/ryayoung/typing-unknown"
repository = "https://github.com/ryayoung/typing-unknown"
documentation = "https://typing-unknown.readthedocs.io"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries"
]
dependencies = []

[dependency-groups]
dev = [
    "pyright>=1.1.401",
    "pytest>=8.4.0",
    "pytest-cov>=6.1.1",
    "ruff>=0.11.12",
    "taskipy>=1.14.1",
]

[tool.taskipy.tasks]
format = "ruff format"
typecheck = "pyright"
tests = "uv run pytest --cov=typing_unknown --cov-branch -vvs --doctest-modules"

[tool.ruff.format]
quote-style = "single"

[tool.pyright]
typeCheckingMode = "strict"
reportMissingParameterType = false
reportUnknownParameterType = false
reportUnusedImport = "error"
