[project]
name = "byteshost-client"
version = "0.1.1"
description = "API wrapper for communicating with the main application"
authors = [
  { name = "Your Name", email = "you@example.com" }
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.8"

[project.urls]
"Homepage" = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
"Bug Tracker" = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
